//User Types
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

//Error Types
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

//Marker Types
export const GET_TOP_MARKERS_START = "GET_TOP_MARKERS_START";
export const GET_TOP_MARKERS_SUCCESS = "GET_TOP_MARKERS_SUCCESS";
export const GET_TOP_MARKERS_FAIL = "GET_TOP_MARKERS_FAIL";
export const MARKER_ADD_START = "MARKER_ADD_START";
export const MARKER_ADD_SUCCESS = "MARKER_ADD_SUCCESS";
export const MARKER_ADD_FAIL = "MARKER_ADD_FAIL";
export const SET_ACTIVE_MARKER = "SET_ACTIVE_MARKER";
export const UNSET_ACTIVE_MARKER = "UNSET_ACTIVE_MARKER";
export const SET_CURRENT_PARENT = "SET_CURRENT_PARENT";
export const UNSET_CURRENT_PARENT = "UNSET_CURRENT_PARENT";
export const CREATE_SUBCONTAINER_START = "CREATE_SUBCONTAINER_START";
export const CREATE_SUBCONTAINER_SUCCESS = "CREATE_SUBCONTAINER_SUCCESS";
export const CREATE_SUBCONTAINER_FAIL = "CREATE_SUBCONTAINER_FAIL";
